### ISSUE TITLE
Crawling process gets connection timed out

### ISSUE THREAD

**Issue by crechberger** [WP2Static/static-html-output-plugin#83] opened 2020-06-05 15:17 UTC
Hi, 
First of all: thank you for creating this wonderful plugin =)

So I'm having some issues with crawling the page, because there seem to be some connectivity issue. 

To give you more context: I host WordPress in a Docker container (virtualization), and outside  URLs such as www.google.com are reachable within the container itself.

So I was wondering what exactly the issue is, why it can't reach the WordPress container itself. Maybe you have some thoughts or technical insights. Did you ever run into a similar problem?

Thanks for your help.

Here's the error log: 
$ cat WP-STATIC-EXPORT-LOG.txt 
2020-06-05 02:26:03
PHP VERSION 7.3.18
OS VERSION Linux 139a654e3ebc 5.4.0-33-generic WP2Static/wp2static#37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64
WP VERSION 5.4.1
WP URL https://www.blog-index.com
WP SITEURL https://www.blog-index.com
WP HOME https://www.blog-index.com
WP ADDRESS https://www.blog-index.com
PLUGIN VERSION 6.6.7
VIA WP-CLI? 
STATIC EXPORT URL http://OFFLINEZIP.wpsho
PERMALINK STRUCTURE /%postname%_%post_id%/
SERVER SOFTWARE Apache/2.4.38 (Debian)
Active plugins:
duplicate-post/duplicate-post.php
js_composer/js_composer.php
revslider/revslider.php
static-html-output-plugin/wp2static.php
updraftplus/updraftplus.php
us-core/us-core.php
wordpress-seo/wp-seo.php
wp-math-captcha/wp-math-captcha.php
Plugin options:
additionalUrls: 
allowOfflineUsage: 1
baseHREF: 
baseUrl: 
baseUrl-bitbucket: 
baseUrl-bunnycdn: 
baseUrl-folder: 
baseUrl-ftp: 
baseUrl-github: 
baseUrl-gitlab: 
baseUrl-netlify: 
baseUrl-s3: 
baseUrl-zip: 
baseUrl-zip: 
basicAuthPassword: *******************
basicAuthUser: 
bbBranch: 
bbPath: 
bbRepo: 
bbToken: *******************
bunnycdnStorageZoneAccessKey: *******************
bunnycdnPullZoneAccessKey: *******************
bunnycdnPullZoneID: 
bunnycdnStorageZoneName: 
bunnycdnRemotePath: 
cfDistributionId: 
completionEmail: 
crawl_delay: 0
crawl_increment: 1
crawlPort: 
debug_mode: 1
detection_level: everything
delayBetweenAPICalls: 0
deployBatchSize: 1
excludeURLs: 
ftpPassword: *******************
ftpRemotePath: 
ftpServer: 
ftpPort: 
ftpTLS: 
ftpUsername: 
ghBranch: 
ghCommitMessage: 
ghPath: 
ghRepo: 
ghToken: *******************
glBranch: 
glPath: 
glProject: 
glToken: *******************
netlifyHeaders: 
netlifyPersonalAccessToken: *******************
netlifyRedirects: 
netlifySiteID: 
removeConditionalHeadComments: 1
removeHTMLComments: 1
removeWPLinks: 1
removeWPMeta: 1
rewrite_rules: 
rename_rules: 
s3Bucket: 
s3Key: 
s3Region: 
s3RemotePath: 
s3Secret: *******************
selected_deployment_option: zip
targetFolder: /var/www/html/mystaticsite
useActiveFTP: 
useBaseHref: 
useBasicAuth: 
useRelativeURLs: 
Installed extensions:
Core
date
libxml
openssl
pcre
sqlite3
zlib
ctype
curl
dom
fileinfo
filter
ftp
hash
iconv
json
mbstring
SPL
PDO
session
posix
Reflection
standard
SimpleXML
pdo_sqlite
Phar
tokenizer
xml
xmlreader
xmlwriter
mysqlnd
apache2handler
bcmath
exif
gd
imagick
mysqli
sodium
zip
Zend OPcache
Exclusion rules wp-json
Crawling /
cURL error:Failed to connect to www.blog-index.com port 443: Connection timed out
BAD RESPONSE STATUS (0): /
Memory allocated by crawl script: 2048
Exclusion rules wp-json
Crawling /another-interesting-single-post_70/
cURL error:Failed to connect to www.blog-index.com port 443: Connection timed out
BAD RESPONSE STATUS (0): /another-interesting-single-post_70/
Memory allocated by crawl script: 2048
Exclusion rules wp-json
Crawling /author-sitemap.xml
cURL error:Failed to connect to www.blog-index.com port 443: Connection timed out
BAD RESPONSE STATUS (0): /author-sitemap.xml
Memory allocated by crawl script: 2048
Exclusion rules wp-json
Crawling /beautiful-scapes_1504/
cURL error:Failed to connect to www.blog-index.com port 443: Connection timed out
BAD RESPONSE STATUS (0): /beautiful-scapes_1504/
Memory allocated by crawl script: 2048

**Comment by leonstafford** [comment] 2020-06-06 04:31
Thanks for the kind words, @crechberger and for reporting this issue.

Quick point: I've since removed the option in the latest builds of the version 6.x.x that you're using, but I can see that `allowOfflineUsage` is enabled in your settings. This is only for creating a zip that can be shared on a local filesystem and won't work on a live site. For offline ZIP creation, I now prefer to point people to using something like [HTTrack](https://www.httrack.com/), but I don't think this is what you're after anyway. For now, removing that option will help once the site actually exports properly (it's not the cause of the connection issues).

For Docker, it's usually a matter of the WordPress Site URL setting not matching the actual webserver address used within the Docker container. As WP2Static is crawling from *within* the container, it needs to be able to resolve that address. It's likely that the container's site is setup for `localhost`, either on port 80 or 443.  

A way to test whether it will work is to SSH into your Docker container and curl/wget your site's url. If it can't resolve this, you may need to add an entry in the `/etc/hosts`file.

Now, a bit more on your intended setup. WP2Static (V6 renaming to "Static HTML Output") is designed to run on a development server, ie dev.example.com. You then publish your static site, using the plugin to rewrite the links to example.com or www.example.com. 

If you're the only person who develops your site, you can run your Docker instance on your local PC and not use TLS/https, so serve over port 80. In this case, I prefer to directly port map localhost:SOMEPORT for the site, ie `docker run -p 4444:4444`, allowing for multiple sites. If you only expect one site, you can map `80:80`, neither of these require any modification to the Docker host to work well. (If you're interested to run locally, I'm starting a new project, [Lokl](https://lokl.dev) which allows to quickly spin up large numbers of WP sites with 1 command)

If you have other remote contributors to the site or prefer to host it online, I suggest adding http basic authentication, to keep the dev server private from bots/indexing/malicious attempts. 

The above is a bit of a ramble. If you could please tell me a bit more about your intended workflow, I'll better advise a specific solution.

**Comment by crechberger** [comment] 2020-06-06 05:42
🙌  Thanks a lot for your answer :)

I only wanted the local environment to test if it's working. What I really want to do is the following: 1. Download the website locally while replacing the url with a different one
2. Run a script which alters the content a little bit
3. Copy all the website files into a nginx docker container, upload the docker container and host it on the server with the url. 

About the connection timeout: I added the blog-index.com to the hosts file and it's now redirecting to localhost, but it's not redirecting the port from 443 to 80. I played around with iptables in the container, but couldn't find a solution yet.
I get "curl: (7) Failed to connect to localhost port 443: Connection refused"

I already moved the WordPress site to a development environment, thank you for the suggestion :)

**Comment by leonstafford** [comment] 2020-06-06 06:19
@crechberger thanks for providing more info. 

Based on that workflow, you may like something more like what I'm using in [Appish](https://appi.sh)

That currently requires `bash` and `wget` to be installed on the machine, but you can see the scripts it's using in the GitHub repo. Basically, just `wget --mirror`'ing the site and replacing all strings: https://github.com/Appish/appi.sh/blob/master/launch.sh

You should be able to have some fun chaining that all up with some `docker build` or Packer or such to deploy the site. 

I'd suggest considering the performance benefits of deploying to a CDN like CloudFront or Cloudflare if you want globally fast speeds. As you'd already have the processed static site files, you could use AWS CLI to sync to S3 or Cloudflare's Workers CLI tool (has some size limitations though) or any other CDN backed static site hosting method, pretty much any "serverless" hosting will support it. 

Back to the current issue, is the SSL being handled within the docker container hosting WordPress or in another load balancer/proxy in front of it? Please share as much as you can about the WP setup, ie docker compose file if you have one

**Comment by crechberger** [comment] 2020-06-06 08:29
Thanks, I'll try Appish out. :)
By the way: A readme is still missing ;)

CDN would be a good idea, but I'll a script which is modifying the contents of the webpage, so it will be a slightly different version than from the WordPress original homepage.

So on the server, there's a reverse proxy (traefik) which ensure that all the communication with the outside world is with https and it redirects to the correct containers. Inside the server all communication is still http. But the issue is still inside the container itself, since I want to redirect the ports. Maybe I can find a solution for that.

**Comment by crechberger** [comment] 2020-06-06 08:30
<img width="1672" alt="screenshot" src="https://user-images.githubusercontent.com/18900864/83939883-f61a0700-a812-11ea-8bc3-9b6b5c62d121.png">

I tried Appish, but there are still some issues (look at the screenshot)

**Comment by crechberger** [comment] 2020-06-06 08:57
<img width="1672" alt="screenshot" src="https://user-images.githubusercontent.com/18900864/83940458-c4a33a80-a816-11ea-87e2-82f90f8be839.png">

Ah well, I forgot to put it in a webserver, so the images now load, but the console errors are the same.

**Comment by leonstafford** [comment] 2020-06-06 13:20
@crechberger cool, I was thinking to just recommend pulling parts out of the Appi.sh script, but cool that it worked. 

There seems to be a cpl issues there:

 - mix of www.localhost and localhost <- where's that coming from?
 - the CSS and JS files are probably containing a 404 error page from WP?

I would try just pulling out the wget command from the appi.sh script, then inspect the downloaded site and make sure everything's there as expected. Look out for the assets in case they've ended up with query strings in filename.

Then if it's all good, use the `sed` command that should also be in that launch.sh script to replace all instances of the original domain with the new intended destination you'll host on. 

You've probably got PHP installed, so this one liner can be a good quick static web hoster:

 - cd into directory of static site files
 - `php -S 0.0.0.0:80` (assuming loose address binding is OK and nothing else on port 80, else when doing test exports, export to localhost:3333 or such and serve with that from php, that can save messing around with nginx configs and copying files around while testing

**Comment by leonstafford** [comment] 2020-06-06 13:32
sorry, reading your earlier comment after last 

> CDN would be a good idea, but I'll a script which is modifying the contents of the webpage, so it will be a slightly different version than from the WordPress original homepage.

What kind of script are you going to use to modify the output? Based on that, may be some more appropriate tooling out there. Also, `wget` is not the best option for downloading sites if you have control over the server. There are more which will do multi-threaded/connection downloading, which should be a lot faster, I don't have the names in mind, but bit of searching around `wget multi-threaded download` is what led me to them before.

Also may depend on how big this operation is for you / how many sites you plan to deploy with custom modifications like this. A scraper written in Python/Ruby/language of preference may do the whole process for you nicely, with better tools than PHP for HTML manipulation (Beautiful Soup, Nokogiri). If it's not too complex a rewrite, then just bash, sed, awk and whatever downloader. There is also a CLI HTML library, like jq for json, called `pup`, great for parsing, not so sure about generating.

> So on the server, there's a reverse proxy (traefik) which ensure that all the communication with the outside world is with https and it redirects to the correct containers. Inside the server all communication is still http. But the issue is still inside the container itself, since I want to redirect the ports. Maybe I can find a solution for that.

I think that's a challenge with such a Docker setup, allowing the web container to resolve the proxy's host in a way that crawling from within WP will work. It may be possible, if you can have that proxy use the same port as the webserver, but seems unnecessarily complicated. 

I think for the least amount of disruption to your current setup, if you can drop the proxy and terminate the SSL in the webserver's box, it will work fine (with same port mapped host:guest).

Easier yet, stick with `wget`, it's available everywhere, free and good at what it does. For some ideas of preventing query strings being saved in filenames: https://superuser.com/questions/61025/how-can-i-make-wget-rename-downloaded-files-to-not-include-the-query-string

**Comment by crechberger** [comment] 2020-06-06 16:28
Unfortunately a SSL port can't be just simply redirected to HTTP, because it throw a certificate error, so I went for the solution to run the wordpress site on localhost and it works.

**Comment by leonstafford** [comment] 2020-06-06 16:58
w00t! Which deploy method did/well you end up using?

**Comment by crechberger** [comment] 2020-06-07 02:03
<img width="1174" alt="screenshot" src="https://user-images.githubusercontent.com/18900864/83958506-4772d680-a8a5-11ea-8b2b-9e94f4d76f3f.png">

I found the reason for the syntax errors. Here for the example "us.core.min.js".

So the JS file on the wordpress site is referred to with using the version as an additional parameter "us.core.min.js?ver=7.5" and Appi downloads and saves the file as "us.core.min.js?ver=7.5", but in the original WP site, the file name of it is "us.core.min.js". So that maybe an enhancement for Appish to ignore the url parameters for JS files.

**Comment by crechberger** [comment] 2020-06-07 02:12
So I could make it work on localhost without using Appish, but your plugin, following your instructions:

> If you're the only person who develops your site, you can run your Docker instance on your local PC and not use TLS/https, so serve over port 80. In this case, I prefer to directly port map localhost:SOMEPORT for the site, ie docker run -p 4444:4444, allowing for multiple sites. If you only expect one site, you can map 80:80, neither of these require any modification to the Docker host to work well. (If you're interested to run locally, I'm starting a new project, Lokl which allows to quickly spin up large numbers of WP sites with 1 command)

**Comment by crechberger** [comment] 2020-06-07 03:47
Also regarding Appish: It would be really cool to have an editable config file so that the export can be automated and the launch script doesn't ask you for user input. 

But that's just another item on the wish list :D 

At this point I already want to thank you for your amazing help and super fast response time 🙌 🥳  Thank you so much :)

**Comment by leonstafford** [comment] 2020-06-09 17:00
closing this one now. have added a guide to debugging this issue at https://www.staticword.press/t/failed-during-crawling-initial-file-list-please-consult-the-help-tab-for-where-to-get-assistance/

**Closed by leonstafford** 2020-06-09 17:00 UTC
Labels: question

**Comment by crechberger** [comment] 2020-06-10 01:07
Thanks! Let me know once the Appish changes are available on Github so I can provide feedback :)

Yes, and thanks for your tools, which you are providing for free :)

All the best on your health and also thanks for creating the plugin guide on this issue.
